name: 'GitHub Traffic Archiver'
description: 'Automatically archive and persist your GitHub traffic and clone metrics beyond the 14-day limit.'
author: 'YOUR-USERNAME'
branding:
  icon: 'database' 
  color: 'green'
  
# This displays the required PAT in the Marketplace UI
inputs:
  token:
    description: 'Personal Access Token (PAT) with "Contents: Write" permissions'
    required: true
    
# This section is required for Marketplace listing
runs:
  using: 'composite'
  steps:
    - run: echo "This is a reusable workflow. Please refer to the README for caller setup."
      shell: bash
